# Used in .github/workflows/build_wheels.yml to run C++ and Python private tests

name: phaseshift-ci
channels:
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - defaults
dependencies:
  - gcc==10.3  # As close as possible as the cibuildwheel gcc (which is uncontrollable)
  - gxx==10.3  # As close as possible as the cibuildwheel gcc (which is uncontrollable)
  - libsndfile==1.2.2
  - libboost==1.89.0
  - libboost-devel==1.89.0
  - libboost-headers==1.89.0
  - fftw==3.3.10
  - fftw-static==3.3.10
  - libflac==1.4.3
  - libvorbis==1.3.7
  - libopus==1.3.1
  - libogg==1.3.5
  - python==3.11
  - cmake==3.31.2
  - pip==25.0.1
  - pip:
    - setuptools==75.8.0
    - ipp-static==2021.12.1
    - numpy==2.2.2
    - scipy==1.15.1
    - soundfile==0.13.1
    - coloredlogs==15.0.1
